---
name: Sync Labels (dotsync)
description: >-
  Sync labels from central config to target repository using dotsync container

inputs:
  token:
    description: GitHub token for API access
    required: true
  org:
    description: Organization name
    required: true
  repo:
    description: Repository name
    required: true
  labels-file:
    description: Path to labels YAML file
    required: true
    default: .github/labels.yml
  sync-config:
    description: JSON sync config from get-sync-config action
    required: false
    default: "{}"
  dry-run:
    description: Dry run (no changes)
    required: false
    default: "false"

runs:
  using: docker
  image: docker://ghcr.io/smykla-labs/dotsync:latest
  args:
    - labels
    - sync
    - --org=${{ inputs.org }}
    - --repo=${{ inputs.repo }}
    - --labels-file=${{ inputs.labels-file }}
    - --config=${{ inputs.sync-config }}
    - --dry-run=${{ inputs.dry-run }}
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
