[tools]
go = "1.26.1"
task = "3.45.5"
golangci-lint = "2.11.3"
actionlint = "1.7.12"
goreleaser = "2.13.0"
jsonschema = "12.10.1"
markdownlint-cli2 = "0.22.0"

[env]
GO111MODULE = "on"
GOFLAGS = "-mod=readonly"
CGO_ENABLED = "0"
