---
branches:
  - main

tagFormat: "dotsync/v${version}"

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: refactor
          release: patch
        - type: chore
          scope: deps
          release: patch
        - type: docs
          release: false
        - type: style
          release: false
        - type: chore
          release: false
        - type: test
          release: false
        - type: ci
          release: false
        - type: build
          release: false

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: Features
          - type: fix
            section: Bug Fixes
          - type: perf
            section: Performance Improvements
          - type: refactor
            section: Code Refactoring
          - type: chore
            scope: deps
            section: Dependencies
          - type: docs
            hidden: true
          - type: style
            hidden: true
          - type: chore
            hidden: true
          - type: test
            hidden: true
          - type: ci
            hidden: true
          - type: build
            hidden: true

  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# Changelog"

  - - "@semantic-release/exec"
    - prepareCmd: |
        sed -i.bak 's|ghcr.io/smykla-labs/dotsync:[0-9.]*|ghcr.io/smykla-labs/dotsync:${nextRelease.version}|g' .github/actions/dotsync/action.yml
        rm -f .github/actions/dotsync/action.yml.bak

  # NOTE: @semantic-release/git removed - using verified-bot-commit action in workflow instead
  # This enables automatic GPG signing via GitHub API

  - "@semantic-release/github"
