---
name: Sync smyklot Version (orgsync)
description: >-
  Update smyklot version references in workflow files using orgsync container

inputs:
  token:
    description: GitHub token for API access
    required: true
  org:
    description: Organization name
    required: true
  repo:
    description: Repository name
    required: true
  version:
    description: smyklot version (e.g., 1.9.2)
    required: true
  tag:
    description: smyklot tag (e.g., v1.9.2)
    required: true
  sync-config:
    description: JSON sync config from get-sync-config action
    required: false
    default: "{}"
  dry-run:
    description: Dry run (no changes)
    required: false
    default: "false"
  orgsync-version:
    description: orgsync container image version
    required: false
    default: latest

runs:
  using: composite
  steps:
    - name: Sync smyklot version with orgsync
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        ORG: ${{ inputs.org }}
        REPO: ${{ inputs.repo }}
        VERSION: ${{ inputs.version }}
        TAG: ${{ inputs.tag }}
        SYNC_CONFIG: ${{ inputs.sync-config }}
        DRY_RUN: ${{ inputs.dry-run }}
        ORGSYNC_VERSION: ${{ inputs.orgsync-version }}
      run: |
        # Build dry-run flag
        DRY_RUN_FLAG=""
        if [ "$DRY_RUN" = "true" ]; then
          DRY_RUN_FLAG="--dry-run"
        fi

        # Build config flag
        CONFIG_FLAG=""
        if [ -n "$SYNC_CONFIG" ] && [ "$SYNC_CONFIG" != "{}" ]; then
          CONFIG_FLAG="--config $SYNC_CONFIG"
        fi

        # Run orgsync in container
        docker run --rm \
          -e GITHUB_TOKEN \
          -v "$PWD:/workspace" \
          -w /workspace \
          "ghcr.io/smykla-labs/orgsync:${ORGSYNC_VERSION}" \
          smyklot sync \
            --org "$ORG" \
            --repo "$REPO" \
            --version "$VERSION" \
            --tag "$TAG" \
            $CONFIG_FLAG \
            $DRY_RUN_FLAG
