name: Get Organization Repositories
description: Get list of repositories in the organization

inputs:
  token:
    description: GitHub token for API access
    required: true
  org:
    description: Organization name
    required: true
    default: smykla-labs

outputs:
  repos:
    description: JSON array of repository names
    value: ${{ steps.repos.outputs.repos }}

runs:
  using: composite
  steps:
    - name: Get repositories
      id: repos
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        ORG: ${{ inputs.org }}
      run: |
        repos=$(gh repo list "$ORG" --json name --jq '[.[].name]')
        echo "repos=$repos" >> "$GITHUB_OUTPUT"
