---
name: Sync Settings (dotsync)
description: >-
  Sync repository settings from central config to target repository using dotsync container

inputs:
  token:
    description: GitHub token for API access
    required: true
  org:
    description: Organization name
    required: true
  repo:
    description: Repository name
    required: true
  settings-file:
    description: Path to settings YAML file
    required: true
    default: .github/settings.yml
  sync-config:
    description: JSON sync config from get-sync-config action
    required: false
    default: "{}"
  dry-run:
    description: Dry run (no changes)
    required: false
    default: "false"

runs:
  using: docker
  image: docker://ghcr.io/smykla-labs/dotsync:1.0.2
  args:
    - settings
    - sync
    - --org=${{ inputs.org }}
    - --repo=${{ inputs.repo }}
    - --settings-file=${{ inputs.settings-file }}
    - --config=${{ inputs.sync-config }}
    - --dry-run=${{ inputs.dry-run }}
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
