---
name: Sync Files (dotsync)
description: >-
  Sync files from central config to target repository using dotsync container

inputs:
  token:
    description: GitHub token for API access
    required: true
  org:
    description: Organization name
    required: true
  repo:
    description: Repository name
    required: true
  files-config:
    description: JSON array of files to sync [{source, dest}, ...]
    required: true
  sync-config:
    description: JSON sync config from get-sync-config action
    required: false
    default: "{}"
  dry-run:
    description: Dry run (no changes)
    required: false
    default: false
  branch-prefix:
    description: Prefix for sync branches
    required: false
    default: chore/org-sync
  pr-labels:
    description: Comma-separated labels for PR
    required: false
    default: ci/skip-all

runs:
  using: docker
  image: docker://ghcr.io/smykla-labs/dotsync:latest
  args:
    - files
    - sync
    - --org="${{ inputs.org }}"
    - --repo="${{ inputs.repo }}"
    - --files-config="${{ inputs.files-config }}"
    - --config="${{ inputs.sync-config }}"
    - --branch-prefix="${{ inputs.branch-prefix }}"
    - --pr-labels="${{ inputs.pr-labels }}"
    - --dry-run="${{ inputs.dry-run }}"
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
